# Generated by Django 4.2 on 2024-10-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'ProductType', 'verbose_name_plural': 'ProductType'},
        ),
    ]
