# Generated by Django 4.2 on 2024-11-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_productimage'),
        ('partner', '0002_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstock',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='catalogue.product'),
        ),
        migrations.AlterField(
            model_name='partnerstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='partner.partner'),
        ),
    ]
